#!/bin/bash

cd <this directory>
. ./venv/bin/activate

IP="yourIP"
startChargingPercentage=15
stopChargingPercentage=80

chargingBool=$(system_profiler SPPowerDataType | grep "Charging" | head -1 | awk '{print $2}')
percentage=$(system_profiler SPPowerDataType | grep "State of Charge (%)" | awk '{print $5}')

if [ "$chargingBool" == 'No' ] && [ "$percentage" -le $startChargingPercentage ]
then
    kasa --host $IP on
elif [ "$chargingBool" == 'Yes' ] && [ "$percentage" -ge $stopChargingPercentage ]
then
    kasa --host $IP off
fi

ECHO $chargingBool
ECHO $percentage
date
