#!/bin/bash

chargingBool=$(system_profiler SPPowerDataType | grep "Charging" | head -1 | awk '{print $2}')
percentage=$(system_profiler SPPowerDataType | grep "State of Charge (%)" | awk '{print $5}')


if [ "$chargingBool" == 'No' ] && [ "$percentage" -le 20 ]
then
    curl -X POST http://homeassistant.local:8123/api/webhook/laptop-battery-G7aFYdOsS9nZfr1i-cKTdwlk -H 'Content-Type: application/json' -d '{"message":    "turn on"}'
elif [ "$chargingBool" == 'Yes' ] && [ "$percentage" -ge 80 ]
then
    curl -X POST http://homeassistant.local:8123/api/webhook/laptop-battery-G7aFYdOsS9nZfr1i-cKTdwlk -H 'Content-Type: application/json' -d '{"messag   e":    "off"}'
else
    ECHO ""
fi

ECHO $chargingBool
ECHO $percentage
date

