#!/bin/bash

launchctl unload ~/Library/LaunchAgents/com.user.battery-script.plist
launchctl load ~/Library/LaunchAgents/com.user.battery-script.plist
launchctl start ~/Library/LaunchAgents/com.user.battery-script.plist
launchctl list | grep com.user.bat

